#!/usr/bin/env python
# -*- coding: UTF-8 *
# vim :et:

import sys
import numpy
import pandas
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

params = plt.rcParams['axes.prop_cycle']
colors = params.by_key()['color']

def make_plot(data):
	ax = plt.figure().gca(projection='3d')
	ax.set_axis_off()
	ax.set_xlim3d(-1,1)
	ax.set_ylim3d(-1,1)
	ax.set_zlim3d(-1,1)

	for j in data.jet.unique():
		jet = data[data.jet == j]
		ax.quiver(0, 0, 0, jet.px, jet.py, jet.pz, \
			arrow_length_ratio=0.05, \
			pivot='tail', color=colors[j%len(colors)])

	plt.show()

if __name__ == "__main__":
	data = pandas.read_csv(sys.argv[1])
	make_plot(data)
