#!/usr/bin/env python
# -*- coding: UTF-8 *
# vim :et:

import sys
import math
import pandas
import matplotlib

# avoid problem when no GUI is available
matplotlib.use('Agg')

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import axes3d

params = plt.rcParams['axes.prop_cycle']
colors = params.by_key()['color']

from sklearn.cluster import KMeans
from sklearn.cluster import AffinityPropagation
from sklearn.cluster import MeanShift
from sklearn.cluster import SpectralClustering
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN

def make_plot(name, data):
	fig = plt.figure(figsize=(16,9))

	jlength = 0.1
	clusters = len(data.jet.unique())
	X = data[['px','py','pz']].as_matrix()

	# KMeans
	kmeans = KMeans(init='k-means++', n_clusters=clusters)
	kmeans.fit_predict(X)
	data['KMeans'] = kmeans.labels_

	# Affinity Propagation
	data['AfProp'] = AffinityPropagation(damping=0.95).fit(X).labels_

	# Mean Shift
	data['MeanShift'] = MeanShift().fit(X).labels_

	# Spectral Clustering
	data['Spectral'] = SpectralClustering(n_clusters=clusters).fit(X).labels_

	# Agglomerative Clustering
	data['Agglomerative'] = AgglomerativeClustering(n_clusters=clusters).fit(X).labels_

	# DBSCAN
	data['DBSCAN'] = DBSCAN().fit(X).labels_

	ax = fig.add_subplot(2, 3, 1, projection='3d')
	ax.set_axis_off()
	ax.set_title('Real classification')
	for j in data.jet.unique():
		jet = data[data.jet == j]
		ax.quiver(0, 0, 0, jet.px, jet.py, jet.pz, length=jlength, color=colors[j%len(colors)])

	ax = fig.add_subplot(2, 3, 2, projection='3d')
	ax.set_axis_off()
	ax.set_title('KMeans')
	for j in data.KMeans.unique():
		jet = data[data.KMeans == j]
		ax.quiver(0, 0, 0, jet.px, jet.py, jet.pz, length=jlength, color=colors[j%len(colors)])

	ax = fig.add_subplot(2, 3, 3, projection='3d')
	ax.set_axis_off()
	ax.set_title('Affinity Propagation')
	for j in data.AfProp.unique():
		jet = data[data.AfProp == j]
		ax.quiver(0, 0, 0, jet.px, jet.py, jet.pz, length=jlength, color=colors[j%len(colors)])

	ax = fig.add_subplot(2, 3, 4, projection='3d')
	ax.set_axis_off()
	ax.set_title('Spectral Clustering')
	for j in data.Spectral.unique():
		jet = data[data.Spectral == j]
		ax.quiver(0, 0, 0, jet.px, jet.py, jet.pz, length=jlength, color=colors[j%len(colors)])

	ax = fig.add_subplot(2, 3, 5, projection='3d')
	ax.set_axis_off()
	ax.set_title('Agglomerative Clustering')
	for j in data.Agglomerative.unique():
		jet = data[data.Agglomerative == j]
		ax.quiver(0, 0, 0, jet.px, jet.py, jet.pz, length=jlength, color=colors[j%len(colors)])

	ax = fig.add_subplot(2, 3, 6, projection='3d')
	ax.set_axis_off()
	ax.set_title('DBSCAN')
	for j in data.DBSCAN.unique():
		jet = data[data.DBSCAN == j]
		ax.quiver(0, 0, 0, jet.px, jet.py, jet.pz, length=jlength, color=colors[j%len(colors)])

	plt.tight_layout()
	plt.savefig(name)

if __name__ == "__main__":
	data = pandas.read_csv(sys.argv[1])
	name = sys.argv[1].replace('.csv','-3d.png')
	make_plot(name, data)
